name: Continuous Integration

on: [push]

jobs:
  ubuntu-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.8
      fail-fast: false


    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Tools
        run: |
          python -m pip install black flake8 pytest

      - name: Linting and Formatting
        run: |
          python -m flake8 ./server/apps/main/views.py --count --select=E9,F63,F7,F82, --ignore=F821 --show-source --statistics
          python -m black --diff ./server/apps/main/views.py

      - name: Run Tests
        run: |
          pytest ./server/apps/main/tests/tests_2023.py