name: Example runfile
on: push

jobs:
  run-tests:
    name: Run basic django test
    runs-on: ubuntu-20.04
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Running composer install
        run: composer install